[package]
name = "fenrir"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["std"] }
regex = { version = "1.12.2", features = ["std"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
strsim = "0.11.1"
indicatif = "0.18.2"
